epoch:
- args:
    iter_num: 1000
    log_interval: 10
    log_vars: [loss, accuracy_top1, accuracy_top5]
  flow: train
  policy: iterate
- args:
    iter_num: 208
    log_vars: [loss, accuracy_top1, accuracy_top5]
  flow: val
  policy: iterate
extra:
  custom_modules: [module]
  custom_paths: [$HOME/prj/few-shot/src]
flows:
- train:
    batch_size: &bs 108
    devices: &gpu gpu(0:2)
    feeder:
      num_thread: &nthread 64
      num_preprocess: &npre 4096
      buffer_size: &buffer_size 10240
      pipeline:
      - attr: {listfile: /home/wangxinglu/prj/few-shot/data/imglst/img10k.train.txt,
               prefix: /home/wangxinglu/prj/few-shot/data/imagenet-raw/,
               shuffle: false,
               allow_io_fail: &allow true,
               thread_num: *nthread,
               shuffle_epoch_num: 10
               }
        expr: data, label = file_list()
#      - expr: data, label = lz_reader()
#        attr:
#          listfile:
#            - $HOME/prj/few-shot/data/imglst/img10k.train.disk.txt
#            - $HOME/prj/few-shot/data/imglst/img10k.train.redis.txt
#          prefix:
#            - $HOME/prj/few-shot/data/imagenet-raw
#            - imagenet
#          addr: 127.0.0.1:2333
#          delim: " "
      - {expr: data = decode(data)}
      - attr: {area_ratios: '0.08:1', aspect_ratio_lb: 0.75, fix_corner: false, mode: multi_scale_area}
        expr: data = crop(data)
#      - attr: {size: 256}
#        expr: data = resize(data)
      - {expr: data = flip(data)}
      - attr: {ratio: 0.5, rotate_lb: -10, rotate_ub: 10}
        expr: data = rotate(data)
      - attr: {size: 224}
        expr: data = resize(data)
      - attr:
          offset: [104, 117, 123]
        expr: data = scaleOffset(data)
    learn:
      lr: 0.0005
      lr_policy: multistep(0.1, 64000,72000,77500)
      min_lr: 1.0e-05
      updater: {momentum: 0.9, type: sgd}
      weight_decay: 0.0005
    spec:
      inputs: [data, label]
      losses: [loss]
      outputs: [loss, accuracy_top1, accuracy_top5]
- val:
    batch_size: *bs
    devices: *gpu
    feeder:
      num_thread: *nthread
      num_preprocess: 1000
      buffer_size: *buffer_size
      pipeline:
      - attr: {listfile: /home/wangxinglu/prj/few-shot/data/imglst/img10k.test.txt,
               prefix: /home/wangxinglu/prj/few-shot/data/imagenet-raw/,
               shuffle: false,
               allow_io_fail: *allow ,
               thread_num: *nthread,
               shuffle_epoch_num: 10
               }
        expr: data, label = file_list()
#      - expr: data, label = lz_reader()
#        attr:
#          listfile:
#            - $HOME/prj/few-shot/data/imglst/img10k.test.disk.txt
#            - $HOME/prj/few-shot/data/imglst/img10k.test.redis.txt
#          prefix:
#            - $HOME/prj/few-shot/data/imagenet-raw
#            - imagenet
#          addr: 127.0.0.1:2333
#          delim: " "
      - {expr: data = decode(data)}
      - attr: {size: 256}
        expr: data = resize(data)
      - attr: {crop_size: 224}
        expr: data = crop(data)
      - attr:
          offset: [104, 117, 123]
        expr: data = scaleOffset(data)
    spec:
      inputs: [data, label]
      losses: [loss]
      outputs: [loss, accuracy_top1, accuracy_top5,data ,label, luzai.cls, prob]
init_missing: true
load_from: $HOME/prj/few-shot/models/resnet101/model.1k.parrots
loggers:
- {type: local}
- args: {password: wxl123, url: 'http://pavi.parrotsdnn.org/log', username: luzai, instance_id:  b6e6d0cb3d8c4890b2f5de683650ecf3}
  type: pavi
max_iter: 160000
model: {yaml: ../meta/res10k.flatten.2048.yaml}
record_best: {factor: -1, field: accuracy_top5, val_flow: val}
snapshot_interval: 5000
work_dir: .
